# Generated by Django 2.0.3 on 2018-07-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataManager', '0002_favtd'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.CharField(max_length=20, verbose_name='用户')),
                ('request', models.TextField(verbose_name='请求参数')),
                ('result', models.TextField(verbose_name='返回结果')),
                ('belong_td', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataManager.TdInfo')),
            ],
            options={
                'verbose_name': '调用历史',
                'db_table': 'record',
            },
        ),
    ]
