# Generated by Django 2.0.3 on 2018-08-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device_name', models.CharField(max_length=20, verbose_name='设备名称')),
                ('manufacturer', models.CharField(max_length=20, verbose_name='厂商')),
                ('model', models.CharField(max_length=20, verbose_name='型号')),
                ('memory_size', models.CharField(max_length=20, verbose_name='内存大小')),
                ('system_version', models.CharField(max_length=20, verbose_name='系统版本')),
                ('belonger', models.CharField(max_length=20, verbose_name='归属人')),
            ],
            options={
                'verbose_name': '设备信息',
                'db_table': 'Device_DeviceInfo',
            },
        ),
    ]
