# Generated by Django 2.0.3 on 2018-08-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='simple_desc',
            field=models.CharField(default=1, max_length=100, verbose_name='归属人'),
            preserve_default=False,
        ),
    ]
