# Generated by Django 2.0.3 on 2018-08-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManager', '0002_deviceinfo_simple_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='lender',
            field=models.CharField(default=1, max_length=20, verbose_name='出借人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='simple_desc',
            field=models.CharField(max_length=100, verbose_name='其他附件'),
        ),
    ]
