# Generated by Django 2.0.3 on 2018-08-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManager', '0003_auto_20180813_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='device_number',
            field=models.CharField(default=1, max_length=50, verbose_name='设备编号'),
            preserve_default=False,
        ),
    ]
