# Generated by Django 2.0.3 on 2018-08-14 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManager', '0004_deviceinfo_device_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operater', models.CharField(max_length=20, verbose_name='操作人')),
                ('device_number', models.CharField(max_length=50, verbose_name='设备编号')),
                ('operate_record', models.TextField(verbose_name='操作记录')),
                ('belong_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeviceManager.DeviceInfo')),
            ],
            options={
                'verbose_name': '操作记录',
                'db_table': 'Device_OperateRecord',
            },
        ),
    ]
