# Generated by Django 2.0.3 on 2018-08-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManager', '0005_operaterecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operaterecord',
            name='belong_device',
        ),
        migrations.AddField(
            model_name='operaterecord',
            name='device_name',
            field=models.CharField(default=1, max_length=50, verbose_name='设备名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deviceinfo',
            name='manufacturer',
            field=models.CharField(max_length=20, verbose_name='品牌'),
        ),
    ]
